export const ACTION_ADD_COMMAND_LINE = "ACTION_ADD_COMMAND_LINE";
export const ACTION_CREATE_CANVAS = "ACTION_CREATE_CANVAS";
export const ACTION_SET_CANVAS_VALUE = "ACTION_SET_CANVAS_VALUE";
export const ACTION_SET_REQUEST_ERROR = "ACTION_SET_REQUEST_ERROR";
export const ACTION_SET_IS_FETCHING = "ACTION_SET_IS_FETCHING";